project21/urls.py
from django.contrib import admin
from django.urls import path,include
import srh,rcb
urlpatterns = [
    path('admin/', admin.site.urls),
    path('rcb/',include('rcb.urls')),
    path('srh/',include('srh.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import *

app_name='rcb'

urlpatterns=[
    path('dupli/',dupli,name='dupli'),
]

srh/urls.py
from django.urls import path
from srh.views import *

app_name='srh'

urlpatterns=[
    path('mak/',mak,name='mak'),
]

rcb/models.py
from django.db import models

# Create your models here.

srh/models.py
from django.db import models

# Create your models here.

rcb/views.py
from django.shortcuts import render

# Create your views here.

def dupli(request):
    return render(request,'dupli.html')

srh/views.py
from django.shortcuts import render

# Create your views here.

def mak(request):
    return render(request,'mak.html')

templates/dupli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this page is rcb</h1>
        <h2><a href="{% url 'srh:mak' %}">go to srh</a></h2>
    </center>
</body>
</html>

templates/mak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this page is srh</h1>
        <h2><a href="{% url 'rcb:dupli' %}">go to rcb</a></h2>
    </center>
</body>
</html>